### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by naz-hage** [naz-hage/ntools#38]
Discussion with @ahmdhjj 
Maintaining documentation is essential.  several places were identified to make the documentation clearer
- Rearrange the [README](https://github.com/naz-hage/ntools/blob/main/README.md) to show list of commands and how to use each of them.
- Add section on how to contribute to the repo
- Add a general section on the use of Developer command prompt and Powershell for Visual Studio 2022
- Document the use of VirusTotal (This feature was added in the [ntools-launcher](https://github.com/naz-hage/ntools-launcher) repo

**Comment by ahmdhjj** [comment]
@naz-hage [mkdocs ](https://www.mkdocs.org/) is one option that can be used to deploy documentation to Github Pages.

In root folder, 2 things are needed:
 - .md files in `/docs`
-  `mkdocs.yml` to configure the pages.

Deployment is done with one command:
```
 mkdocs gh-deploy
 ```
 
 In the meantime, I opened #40 to update the README which might be sufficient for us.
 We can also implement mkdocs in a separate branch and see how it looks. Let me know what you think.

**Comment by naz-hage** [comment]
Thanks Ahmad. Let's try implementing mkdocs in this branch: issue38.  For now, we assume the documentation is good.

**Comment by ahmdhjj** [comment]
@naz-hage can you please enable Github pages in the repo settings and configure it to publish from branch: `gh-pages`?

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch

**Comment by naz-hage** [comment]
@ahmdhjj I have enabled publishing from `gh-pages`

**Comment by ahmdhjj** [comment]
Thank you @naz-hage, can you please check the docs deployed at https://naz-hage.github.io/ntools/? I have updated this PR:
- Shortened README and included the link to docs
- Add mkdocs configuration and docs/ dir

If you think everything looks good, the next step would be to set a workflow (or at least add instructions on how to) deploy the docs.
