### ISSUE TITLE
Unable to complete the installation of NTools

### ISSUE THREAD

**Issue by naz-hage** [naz-hage/ntools#41]
**Describe the bug**
Following the README, the INSTALL.PS1 fails to install the Ntools.  The PATH is not updated with NTools location `c:\program files\nbuild`

**To Reproduce**
On Windows 11 PC
1. Login to a Standard user (A user with no admin priveledges)
2. Start an Admin PowerShell
3. Clone https://github.com/naz-hage/ntools
4. switch to the ntools folder
5. Follow the instructions in the [README](https://github.com/naz-hage/ntools/blob/issue38/README.md)
6. See the error: 
- Failed to display git info: File C:\source\ntools\resources\INFO: Could not find the file specified or the given pattern(s). not found 

**Expected behavior**
The INSTALL.PS1 script should have installed all the development tools required and adds the the `c:\program files\nbuild`  to the User PATH envieonment. variable.  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by naz-hage** [comment]
@LuhitYoung  Can you please verify the fix in the latest release of Ntools version 1.3.23?
- Pull latest source from Ntools main branch
- Follow installation instructions on https://naz-hage.github.io/ntools/installation/

**Comment by Maxasoft** [comment]
Solved
