### ISSUE TITLE
Remove hardcoded repo folder (C:\source) from Install.ps1.

### ISSUE THREAD

**Issue by Maxasoft** [naz-hage/ntools#42]
It would be advantageous to have the tools to be installed from any folder where the NTools repository has been cloned to.

**Comment by naz-hage** [comment]
Fixed in PR #43 @Maxasoft can you confirm that this sets the DevDrive and MainDir environments different from default values on specified on the command line with `install.ps1`

**Comment by Maxasoft** [comment]
Solved and integrated into main.
