### ISSUE TITLE
Feature: Harden and release `ntools` version 1.5.0

### ISSUE THREAD

**Issue by naz-hage** [naz-hage/ntools#58]
**Acceptance Criteria:**
-  Review deployed documentation
- Respond to issues found in [getting-started](https://github.com/naz-hage/getting-started) repo. 
  - This repo demonstrates the use of setting up a project and use ntools
- Release version 1.5.0

**Comment by ahmdhjj** [comment]
A few notes regarding the docs:
- In the [setup page](https://naz-hage.github.io/ntools/setup/), the command below must be corrected (`-tag`):
```
ng -c settag tag 0.0.1 
```
- The section right below the command above has some redundancy in explaining folder structure
- It would be better if for the section [Add a new task](https://naz-hage.github.io/ntools/setup/#add-a-new-task), we improve the example by adding another task to existing example (right now the example is used for `Add a new target` so it might not be very easy to tell the difference between target and task)

**Comment by ahmdhjj** [comment]
A few notes regarding `DevSetup`:

-  `DevSetup.ps1`  is outdated, the location of `install.psm1` has changed
- [DevSetup folder section](https://naz-hage.github.io/ntools/setup/#devsetup-folder) doesn't mention `apps-Ntools.json` which is needed.
- [Add a new tool section](https://naz-hage.github.io/ntools/setup/#add-a-new-tool) mentions that you can install the apps using the CLI but that is already covered in the script above.
- It would be helpful to suggest to modify the sample `DevSetup.ps1` according to your project's needs

**Comment by naz-hage** [comment]
resolved in #59
